name: Schedule Script Test
on:
  schedule:
    - cron: '0 */1 * * 1-5'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "script done!"
      - run: sh main.sh
